### ISSUE TITLE
Unable to download weights due to region issues

### ISSUE THREAD

**Issue by ialhashim** [hahazh/OFR-BRN#1]
Is it possible to upload the pre-trained weights to github or some other cloud provider than Baidu?

**Comment by jyang297** [comment]
https://www.dropbox.com/scl/fi/txhjl4acez26b0rbfd9ak/ofr-brn.pth?rlkey=9lsz0lur89ewadmb26z242z30&dl=0

Hello,

I download it and upload it to dropbox. I am not sure how long the link can be available. This is the first time I use dropbox to share something.

btw, I met some problem in implement the code. There are something wrong with snippets using mmcv I guess. Hope you will not meet those questions and give me a feedback.

**Comment by hahazh** [comment]
please refer to https://github.com/open-mmlab/mmcv for more detailed installation guidance of mmcv.
my mmcv version is 1.3.16 and my torch version is '1.10.0+cu111'.

**Comment by hahazh** [comment]
> https://www.dropbox.com/scl/fi/txhjl4acez26b0rbfd9ak/ofr-brn.pth?rlkey=9lsz0lur89ewadmb26z242z30&dl=0
> 
> Hello,
> 
> I download it and upload it to dropbox. I am not sure how long the link can be available. This is the first time I use dropbox to share something.
> 
> btw, I met some problem in implement the code. There are something wrong with snippets using mmcv I guess. Hope you will not meet those questions and give me a feedback.

Thank you very much. The link you provided has been updated in the readme.
