### ISSUE TITLE
Hello author, is there any training script

### ISSUE THREAD

**Issue by fzuqxt** [hahazh/OFR-BRN#2]
Hello author, is there any training script

**Comment by fzuqxt** [comment]
can you give me an e-mail address?

**Comment by hahazh** [comment]
Thanks for your attention！
We used the same training strategy as Zooming SlowMo. You can refer to it for guidance：
https://github.com/Mukosame/Zooming-Slow-Mo-CVPR-2020/blob/master/codes/train.py

**Comment by fzuqxt** [comment]
你好，作者，我尝试用zoomingslowmo的训练脚本，但是会出现梯度报错的问题，是否有更详细的训练脚本文件呢






qiuxt
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hahazh/OFR-BRN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月20日(星期五) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hahazh/OFR-BRN] Hello author, is there any training script (Issue #2)





 
Closed #2 as completed.
